# Generated by Django 3.2.5 on 2021-07-26 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20210726_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='task',
            new_name='text',
        ),
    ]
